### ISSUE TITLE
Add support for custom tags like "due:"

### ISSUE THREAD

**Issue by davideferre** [jmhobbs/jsTodoTxt#12]
It would be nice if you add support for custom tags.
I'm using gnome extension for todo.txt and editing todo.txt file I'm adding due date tag but I see the due date at the end of the task text.
Example:
> Test task due:2018-10-15

**Comment by jmhobbs** [comment]
The `DueExtension` should be able to help you out, in the `jsTodoExtensions.js` file.  You must pass them in when creating your `TodoTxtItem`.  This should probably be called out in the documentation though.

<img width="473" alt="screen shot 2018-10-02 at 9 44 17 am" src="https://user-images.githubusercontent.com/115059/46356157-c5d69a00-c627-11e8-8a30-3992e071e120.png">

**Comment by davideferre** [comment]
Yes, I found it.
I've also found a small bug in DueExtension parsing function, you return always:
`return [dueDate, line.replace(dueRegex, ''), matchDue[1]];`
but if matchDue is null you get an error.
The return statement must be placed into the if statement and another return statement like this:
`return [null, null, null];`
must be placed after the if.
I create a pull request for that fix.

**Comment by jmhobbs** [comment]
Good catch, thanks for the fix.

**Comment by jmhobbs** [comment]
I opened #15 to surface this knowledge in the README.  Thanks!
