### ISSUE TITLE
"ReferenceError: TodoTxtExtension is not defined" when trying to use extensions 

### ISSUE THREAD

**Issue by jmanuel1** [jmhobbs/jsTodoTxt#20]
In Node, when I try to pass in an extension to the `TodoTxtItem` constructor, I get a `ReferenceError: TodoTxtExtension is not defined` error. I'm able to import and log `TodoTxtExtension` from my code. From a glance at the source, it looks like `jsTodoTxt.js` doesn't require from `jsTodoExtensions.js`, so the `TodoTxtExtension` name is never introduced in that module's scope.

Right now, I think I can work around it by assigning `TodoTxtExtension` to `global.TodoTxtExtension` so that it's visible everywhere.

**Comment by jmhobbs** [comment]
Sorry, very late on the reply here.  The original idea was that you could use the main lib without the extensions, if you wanted, or provide your own implementations of them.

Is this a documentation issue, or something we should solve by packaging them together?  Keep in mind this is largely 2011 code, so it's way behind modern patterns (as am I :)

**Comment by jmanuel1** [comment]
Packaging them together could fix it. I think #26 could also fix it. But if the extensions lib should be optional, I guess in Node it could be `require`d only when used? I'm not sure how that problem is usually solved myself 😆 

I's say it could be documentation issue, but I don't think it's common to add properties to `global` for this kind of reason.
