### ISSUE TITLE
Minor issue when using double plus (++) and a proper project

### ISSUE THREAD

**Issue by ransome1** [jmhobbs/jsTodoTxt#29]
Hi @jmhobbs.

a [sleek](https://github.com/ransome1/sleek/issues/128) user is reporting an interesting behavior, which I think is connected to some regex configuration in jsTodoTxt (sleek is using v0.9.0 of jsTodoTxt) and I would like to pass it on to you, if you don't mind.

The issue occurs while creating the todotxt object, when a double plus is used and a project follows. The example provided to me is `(A) My C++ todo +project`. This will create a todotxt object, which when converted back to a string, will result in `(A) My C todo +project`.

![image](https://user-images.githubusercontent.com/11188741/119964100-20774e00-bfa9-11eb-9a0b-37f135fd94cf.png)

This only happens when a proper project is passed later on. If not the double plus won't case any issue, for instance `(A) My C++ todo` will result in `(A) My C++ todo`.

The same behavior can be produced with contexts: `(A) My C@@ todo @project`

As far as I know, this shouldn't clash with the todo.txt rule set. Do you any idea what does cause it?

Looking forward hearing from you.

**Comment by zerodat** [comment]
I think that this is a bug in the `_project_replace_re` pattern in `jsTodoTxt.js`.  The existing pattern is:
```
_project_replace_re:  /\s*\+\S+\s*/g,
```
which is too aggressive at removing anything after a plus sign, but if it is changed to:
```_project_replace_re:  /(^|\s+)\+\S+\s*/g,
```
it seems to work fine for me.

**Comment by ransome1** [comment]
Thanks for the PR @zerodat !

**Comment by jmhobbs** [comment]
Added another test to cover as well 👍

**Comment by ransome1** [comment]
@jmhobbs lovely. Any plan on releasing it to npm any time soon?

**Comment by jmhobbs** [comment]
Good idea!  Released as 0.10.0 since there are some other interface enhancing changes in there too.

**Comment by zerodat** [comment]
Thanks, @jmhobbs !

**Comment by ransome1** [comment]
@zerodat, just tested `(A) My C@@ todo @project` in sleek and it still produces `(A) 2021-06-08 My C todo @project` :/

**Comment by zerodat** [comment]
Hmmm.  OK, let me take a look.

**Comment by zerodat** [comment]
It works fine in my own build where I am using a version of jsTodoTxt that I fixed myself.  Can you examine your `node_modules/jstodotxt/jsTodoTxt.js` to make sure that the replacement patterns are correct there?

**Comment by zerodat** [comment]
@ransome1 I updated my node_module with `yarn -L -P jstodotxt` so that I got 0.10.0, rebuilt sleek, and tested again.  Seems to be working fine for me.

**Comment by ransome1** [comment]
I deleted my whole node_modules folder and reinstalled it with yarn. Let me see if there is a cache issues involed.

What's odd is the commit, the 0.10.0 has been built from: https://github.com/jmhobbs/jsTodoTxt/blob/05ba74c1e681fb75f0fc1c63ee195f6915ea765e/jsTodoTxt.js

In line 29 it reads: 
`_project_replace_re:  /(^|\s+)\+\S+/g,`

Your suggestion was: 
`_project_replace_re:  /(^|\s+)\+\S+\s*/g,`

**Comment by zerodat** [comment]
I think that the patterns in 0.10.0 are correct.  I made more than one commit to my branch.  My first commit was what you described, with the `\s*` at the end, but that will eat up too many spaces and keep the matching from working if there is more than one project or context, so I ended up with the `_project_replace_re:  /(^|\s+)\+\S+/g,` and `_context_replace_re: /(^|\s+)@\S+/g,` patterns.  (See commit https://github.com/zerodat/jsTodoTxt/commit/9ebdf5bf202654ffbf147a670722295b591750f4).  Not sure why this isn't working for you, but 0.10.0 seems to work for me in sleek.

**Comment by ransome1** [comment]
@zerodat . it works now and I have no idea why ;) Anyway, good work.
