### ISSUE TITLE
How does jsTodoTxt (next) detect an extension?

### ISSUE THREAD

**Issue by ransome1** [jmhobbs/jsTodoTxt#42]
Hi there.

Good jobs on the `next` branch, I successfully deployed it into my project and it works well.

Back in `0.1.0` we were able to define extensions. Specific patterns in the string were extracted as extensions and thus were available in the todo object.

How would I do the same in `next`? Let's say I want `#TestTag1`, `#TestTag2` and `#TestTag3` (part of the string) recognized as `tags` and put into the extensions key `tags` 

Thanks for your support.

**Comment by jmhobbs** [comment]
Hmm, I'm not sure here.  This is the design I have for extensions, https://github.com/jmhobbs/jsTodoTxt/pull/36

It is designed 100% around the `<key>:<value>` style defined in the spec https://github.com/todotxt/todo.txt#additional-file-format-definitions

I think for something like `#TestTag1` that might need to be something that post-processes the Item somehow.  I'm open to suggestions though!

**Comment by jmhobbs** [comment]
I think most of the difficulty is in keeping tags in the same position when modified, which was a weakness in how the original system worked, it would move new/altered tags to the end of the line.

**Comment by ransome1** [comment]
I think can work around it somehow. And you're right, the arbitrary positioning of attributes should not be altered. It's working very well in the next branch :)
