### ISSUE TITLE
@ or + in middle of sentece

### ISSUE THREAD

**Issue by bjorngi** [jmhobbs/jsTodoTxt#5]
If you type @ or + in the middle of a sentence you wont be able to build up the original task.
Example: "Find phone and @call lisa at @work" will leave you with "Find phone and lisa at @work @call"

**Comment by Wuestengecko** [comment]
+1 on this, I'd like to have my `+projects` at the beginning of the line for easier sorting. I've brought this up previously in [the todo.txt GNOME shell extension](https://gitlab.com/bartl/todo-txt-gnome-shell-extension/issues/115), which is based on this library. Unfortunately the report there hasn't seen much love either.

**Comment by Tobida** [comment]
+1 on this, i opened a ticket at the sleek project, which is using your library. 

I love to use todo.txt in a natural way of language:

>    discuss with @george about +superproject concerning the aspect of unicorns

using jsTodoTxt  it will show up like this, the sentence is destroyed

>    discuss with about concerning the aspect of unicorns @george +superproject

**Comment by xuhcc** [comment]
I think one way to achieve this is to do the following:
- Remember the initial line during `TodoTxtItem` initialization.
- Replace attributes like `text` and `priority` with getters and setters.
- `TodoTxtItem` should keep a change log. Every time you call a setter, a new operation is added to the log.
- `toString()` should iterate over the change log and mutate the initial line instead of reconstructing it from scratch.

**Comment by jmhobbs** [comment]
Cool, I think I get it.  This will be an API breaker, so it'll be a version bump.  I'll start working on a possible implementation.

**Comment by ransome1** [comment]
> Cool, I think I get it. This will be an API breaker, so it'll be a version bump. I'll start working on a possible implementation.

That will be a great improvement and over at the [sleek](https://github.com/ransome1/sleek) project, which is based on your great work here, we will appreciate your effort!

**Comment by intrepidsilence** [comment]
Indeed, it would be great to have this feature. This reduces the duplication of wording in an item and can make it much more readable.

**Comment by Toffanelly** [comment]
Very useful feature! Looking forward to it. Thanks for your work.

**Comment by dnngll** [comment]
+1, super important imho

**Comment by aubreyz** [comment]
I agree. Critical to eliminate this problem (it us a bug in fact)

**Comment by ransome1** [comment]
@jmhobbs Hey how are you? Do you think there will be work on this at some point? We are still a bit struggling with this missing functionality over at sleek. 

Cheers :)

**Comment by aubreyz** [comment]
+10 for this. There is no reason ever to change the data line, and it completely destroys the usability of other great apps such as Sleek.

**Comment by aisbergde** [comment]
It looks like other projects (sleek) depends on this feature.

**Comment by jmhobbs** [comment]
Hey all!   A long time coming, but I have a draft of an API change to support this.  Still lots to sort out, but I would appreciate any feedback you can give.

Check out #33

Thanks!

**Comment by jmhobbs** [comment]
We are underway!  I've updated the primary branch to `next` and you can try out the API with `npm install jstodotxt@next`, though consider it unstable as I iterate on it.  Expecting to land it next week, I want to build a toy app or two to get a feel for using it.  Docs are up here: https://next--grand-bunny-8f4598.netlify.app/
