### ISSUE TITLE
Could you update npm?

### ISSUE THREAD

**Issue by 1egoman** [jmhobbs/jsTodoTxt#7]
I'm thinking about doing something with node, but the npm version isn't up to date. Could you publish the latest version?

**Comment by jmhobbs** [comment]
Sorry about that, I forgot NPM doesn't update itself from github like packagist :)

0.6.0 is up now.

**Comment by Cherkah** [comment]
npm version isn't up to date. Could you publish the latest version?
thx

**Comment by jmhobbs** [comment]
0.7.0 up 👍
